name: "conditional_captioning"
backend: "python"
max_batch_size: 8
input [
  {
    name: "INPUT"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "FOOD_LABEL"
    data_type: TYPE_STRING  # additional text input from food classifier
    dims: [1]
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_STRING
    dims: [1]
  }
]
