name: "conditional_captioning"
backend: "python"
max_batch_size: 1
input [
  {
    name: "INPUT"
    data_type: TYPE_STRING  # Input image sent as a base64 encoded string
    dims: [1]
  },
  {
    name: "FOOD_LABEL"
    data_type: TYPE_STRING  # additional text input from food classifier
    dims: [1]
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_STRING  # Generated caption through BLIP
    dims: [1]
  }
]
