name: "image_caption_gpu"
backend: "python"
max_batch_size: 8
instance_group [
  {
    kind: KIND_GPU
    count: 1
    gpus: [0]
  }
]
input [
  {
    name: "INPUT"
    data_type: TYPE_STRING
    dims: [1]
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_STRING
    dims: [1]
  }
]
